### ISSUE TITLE
Not able to retrieve Traffic stats

### ISSUE THREAD

**Issue by Romanmir** [gruijter/netgear.js#1]
I'm not sure where I'm going wrong here.
When I try to use any of the authenticated functions, I get the following message:

`Error: Not logged in
    at Promise (/data/node/traffic/node_modules/netgear/netgear.js:738:19)
    at new Promise (<anonymous>)
    at NetgearRouter._makeRequest (/data/node/traffic/node_modules/netgear/netgear.js:736:10)
    at Promise (/data/node/traffic/node_modules/netgear/netgear.js:563:9)
    at new Promise (<anonymous>)
    at NetgearRouter.getTrafficMeter (/data/node/traffic/node_modules/netgear/netgear.js:561:10)
    at Object.<anonymous> (/data/node/traffic/traffic.js:15:8)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)`

My code is dead simple, but I am still learning Node.
My code looks like this:
[traffic.js.log](https://github.com/gruijter/netgear.js/files/2281368/traffic.js.log)

My full output is attached (TrafficOutput.log)
[TrafficOutput.log](https://github.com/gruijter/netgear.js/files/2281366/TrafficOutput.log)

Thoughts?

**Comment by gruijter** [comment]
Hi romanmir

To get trafficmeter stat you need to be logged in first. So put the code for trafficstats inside the .then of the code for login. Or use async-await when you do not want to use .then

Keep trying 😀. The asynnchronous stuff of node is a pain, but I managed to understand it enough after a lot of reading and trial.
