### ISSUE TITLE
Add Netgear Switches? 

### ISSUE THREAD

**Issue by BolverBlitz** [gruijter/netgear.js#12]
Do the Netgear Smart Manages Plus switches also support SOAP? 
I would love to acces my GS110EMX

**Comment by gruijter** [comment]
I dont think so. But just install the package and run the test:

` > npm test password=mySecretPassword host=ip.ad.re.ss`

**Comment by BolverBlitz** [comment]
Nope :/

```
Testing now. Hang on.....
========== STARTING TEST ==========
Node version: v10.16.3
Netgear package version: 4.0.3
OS: win32 10.0.18362
t = 0
trying to auto discover Netgear routers...
Error: No Netgear router could be discovered
    at NetgearRouter._discoverAllHostsInfo (C:\Users\1515\Desktop\Test\netgear.js-master\netgear.js:1496:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
NetgearRouter {
  host: '192.168.1.7',
  port: undefined,
  tls: false,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: undefined,
  loggedIn: false,
  configStarted: false,
  soapVersion: undefined,
  loginMethod: undefined,
  getAttachedDevicesMethod: undefined,
  checkNewFirmwareMethod: undefined,
  guestWifiMethod:
   { set24_1: undefined, get50_1: undefined, set50_1: undefined },
  lastResponse:
   Error: No Netgear router could be discovered
       at NetgearRouter._discoverAllHostsInfo (C:\Users\1515\Desktop\Test\netgear.js-master\netgear.js:1496:11)
       at process._tickCallback (internal/process/next_tick.js:68:7) }
```
