### ISSUE TITLE
Discovery not working well / port 5555

### ISSUE THREAD

**Issue by vyasbhavin** [gruijter/netgear.js#20]
Hi,
I get the most basic of errors, unable to login. Confirmed that the password is accurate by logging in to the UI.

The test code is a copy / paste from the instructions. 

```
// create a router session, login to router, fetch attached devices
const Netgear = require('netgear');

const router = new Netgear();

async function getDevices() {
        try {
                const options = { password: '****', method: 0, host: 'routerlogin.net', username: 'admin', port: 80 };
                await router.login(options);
                const deviceArray = await router.getAttachedDevices();
                console.log(deviceArray);
        } catch (error) {
                console.log(error);
        }
}

getDevices();

```
Router is a supported version: R6400v2
I have a Nighthawk App and Circle, which both are able to connect to the router, so assuming the API connection is working.

I get `Error: Failed to login`

Any thoughts on where I can look further to debug?

**Comment by gruijter** [comment]
Can you post the full test response? Use 'npm test password=whateveritis' from the netgear folder.

**Comment by vyasbhavin** [comment]
For sure. 

```Testing now. Hang on.....
========== STARTING TEST ==========
Node version: v14.15.4
Netgear package version: 4.4.1
OS: darwin 20.6.0
t = 0
trying to auto discover Netgear routers...
Error: No Netgear router could be discovered
    at NetgearRouter._discoverAllHostsInfo (/Users/bhavin/node_modules/netgear/netgear.js:1774:11)
    at async getRouterInfo (/Users/bhavin/node_modules/netgear/test/_test.js:85:13)
    at async Object.exports.test (/Users/bhavin/node_modules/netgear/test/_test.js:524:3)
NetgearRouter {
  host: 'routerlogin.net',
  port: undefined,
  tls: true,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: undefined,
  loggedIn: false,
  configStarted: false,
  soapVersion: undefined,
  loginMethod: undefined,
  getAttachedDevicesMethod: undefined,
  checkNewFirmwareMethod: undefined,
  guestWifiMethod: { set24_1: undefined, get50_1: undefined, set50_1: undefined },
  lastResponse: Error: No Netgear router could be discovered
      at NetgearRouter._discoverAllHostsInfo (/Users/bhavin/node_modules/netgear/netgear.js:1774:11)
      at async getRouterInfo (/Users/bhavin/node_modules/netgear/test/_test.js:85:13)
      at async Object.exports.test (/Users/bhavin/node_modules/netgear/test/_test.js:524:3),
  queue: SmartQueue {
    queue: Map(0) {},
    overheat: 1645874068562,
    pending: false,
    params: {
      default: [Object],
      rules: [Object],
      overall: [Object],
      retryTime: 2,
      ignoreOverallOverheat: true
    },
    heatPart: 100
  }
}
```

Very strange that it's unable to discover a Netgear route, I wonder if there is a Netgear setting that I need to enable for discovery, though Nighthawk App and Circle are both working and able to connect

UPDATE:

Running it a second time, discovery works and I get the `Failed to login` error. Here's the full message. 
```
Testing now. Hang on.....
========== STARTING TEST ==========
Node version: v14.15.4
Netgear package version: 4.4.1
OS: darwin 20.6.0
t = 0
trying to auto discover Netgear routers...
[
  {
    Firmware: 'V1.0.4.122_10.0.95',
    RegionTag: 'R6400v2_NA',
    Region: 'us',
    Model: 'R6400v2',
    InternetConnectionStatus: 'Up',
    ParentalControlSupported: '1',
    CircleEnabled: '1',
    OpenDNSEnabled: '0',
    SOAPVersion: '3.21',
    ReadyShareSupportedLevel: '29',
    XCloudSupported: '1',
    LoginMethod: '2.0',
    DeviceMode: '0',
    SOAP_HTTPs_Port: '5555',
    host: '192.168.1.1',
    port: undefined,
    tls: false
  }
]
t = 2.035
trying to login using method 1...
method 1 failed.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
Error: Failed to login
    at NetgearRouter.login (/Users/bhavin/node_modules/netgear/netgear.js:232:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getRouterInfo (/Users/bhavin/node_modules/netgear/test/_test.js:101:3)
    at async Object.exports.test (/Users/bhavin/node_modules/netgear/test/_test.js:524:3)
NetgearRouter {
  host: 'routerlogin.net',
  port: undefined,
  tls: false,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: undefined,
  loggedIn: false,
  configStarted: false,
  soapVersion: 3,
  loginMethod: 2,
  getAttachedDevicesMethod: undefined,
  checkNewFirmwareMethod: undefined,
  guestWifiMethod: { set24_1: undefined, get50_1: undefined, set50_1: undefined },
  lastResponse: 401,
  queue: SmartQueue {
    queue: Map(1) { 1645875957310 => [Object] },
    overheat: 1645875951235,
    pending: true,
    params: {
      default: [Object],
      rules: [Object],
      overall: [Object],
      retryTime: 2,
      ignoreOverallOverheat: true
    },
    heatPart: 100
  }
}
```

**Comment by gruijter** [comment]
Ah, that is already helpful. It seems your soap port is 5555.

So try this:
npm test password=yourpass host=192.168.1.1 port=5555 tls=true

**Comment by vyasbhavin** [comment]
Super useful, much appreciated @gruijter! that solved it. In my JS script, I also have to explicitly specify username='admin' - but then it works. Thanks for your help!

**Comment by gruijter** [comment]
Super!
I will keep this issue open however, because your settings should have been detected during autodiscovery.

Guess I need to figure out why it is going wrong. It might be a timing issue since you got a different result the second time running the discovery.

Thx for the feedback!

**Comment by gruijter** [comment]
Can you try to run the test again with the new version 4.4.2?

Use `npm test password=yourpass`

**Comment by vyasbhavin** [comment]
Sure @gruijter 

Still failing with just that ```Testing now. Hang on.....
========== STARTING TEST ==========
Node version: v14.15.4
Netgear package version: 4.4.2
OS: darwin 20.6.0
t = 0
trying to auto discover Netgear routers...
[
  {
    Firmware: 'V1.0.4.122_10.0.95',
    RegionTag: 'R6400v2_NA',
    Region: 'us',
    Model: 'R6400v2',
    InternetConnectionStatus: 'Up',
    ParentalControlSupported: '1',
    CircleEnabled: '1',
    OpenDNSEnabled: '0',
    SOAPVersion: '3.21',
    ReadyShareSupportedLevel: '29',
    XCloudSupported: '1',
    LoginMethod: '2.0',
    DeviceMode: '0',
    SOAP_HTTPs_Port: '5555',
    host: '192.168.1.1',
    port: undefined,
    tls: false
  }
]
t = 4.008
trying to login using method 1...
method 1 failed.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
Error: Failed to login
    at NetgearRouter.login (/Users/bhavin/node_modules/netgear/netgear.js:232:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getRouterInfo (/Users/bhavin/node_modules/netgear/test/_test.js:101:3)
    at async Object.exports.test (/Users/bhavin/node_modules/netgear/test/_test.js:524:3)
NetgearRouter {
  host: 'routerlogin.net',
  port: undefined,
  tls: true,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: undefined,
  loggedIn: false,
  configStarted: false,
  soapVersion: 3,
  loginMethod: 2,
  getAttachedDevicesMethod: undefined,
  checkNewFirmwareMethod: undefined,
  guestWifiMethod: { set24_1: undefined, get50_1: undefined, set50_1: undefined },
  lastResponse: 401,
  queue: SmartQueue {
    queue: Map(1) { 1646000200172 => [Object] },
    overheat: 1646000192075,
    pending: true,
    params: {
      default: [Object],
      rules: [Object],
      overall: [Object],
      retryTime: 2,
      ignoreOverallOverheat: true
    },
    heatPart: 100
  }
}
```

**Comment by JackAida** [comment]
I know this issue request is quite old , but one of the things I have been doing to ensure that I can connect is:
```javascript
        var loginOptions = {}; //creating an array to store the login options
        const currentSetting = await router.getCurrentSetting(); //getting the routers settings which also happens to have port information
	loginOptions['password'] = 'PASSWORD';
	loginOptions['username'] = 'admin';
	loginOptions['timeout'] = 60000; //no idea what time out does to be honest I just made it long assuming its how long it takes to get logged out
	loginOptions['port'] = currentSetting.port; //set the port to the correct port for logging in
	loginOptions['host'] = '192.168.1.1';
	router.login(loginOptions); //login using the settings provided above
```
Doing the above it self identifies its required port using the getCurrentSetting() which works without being logged in to the router

EDIT: I just noticed in the above message that port was Undefined, based on that im not certain that my method in this would work, unless getCurrentSetting() also has the SOAP_HTTPs_PORT as a key/value (havent checked) if it does can do something like: loginOptions['port'] = (currentSetting.port) ? currentSetting.port : currentSetting.SOAP_HTTPs_PORT; (this is if this key exists)

**Comment by gruijter** [comment]
try new v5
