### ISSUE TITLE
Cannot reboot Netgear Nighthawk M1100

### ISSUE THREAD

**Issue by shiipou** [gruijter/netgear.js#9]
Hi there, 
I have a problem with my M1100 router.
It lost my internet connexion every night, So, to resolve this problem, I want to reboot it everyday at 5am.

I tried your node solution, but I got an error 👍 

```console
[imeniyu@odinn netgearctl]$ npm start

> netgear@0.0.1 start /mnt/c/Users/Flavien CADET/Documents/dev/netgearctl
> node netgear.js

Log in...
Logged in : true
Error: Reboot request failed. (config started failure: Error: Config started error: Error: HTTP request Failed. Status Code: 401)
    at _configurationStarted.catch (/mnt/c/Users/Flavien CADET/Documents/dev/netgearctl/node_modules/netgear/netgear.js:697:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netgear@0.0.1 start: `node netgear.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the netgear@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/imeniyu/.npm/_logs/2019-02-15T18_42_32_153Z-debug.log
[imeniyu@odinn netgearctl]$ cat /home/imeniyu/.npm/_logs/2019-02-15T18_42_32_153Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/sbin/npm', 'start' ]
2 info using npm@6.8.0
3 info using node@v11.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle netgear@0.0.1~prestart: netgear@0.0.1
6 info lifecycle netgear@0.0.1~start: netgear@0.0.1
7 verbose lifecycle netgear@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle netgear@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/Flavien CADET/Documents/dev/netgearctl/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/Microsoft VS Code Insiders/bin:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Users/Flavien CADET/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Flavien CADET/Documents/WSL/Arch:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle netgear@0.0.1~start: CWD: /mnt/c/Users/Flavien CADET/Documents/dev/netgearctl
10 silly lifecycle netgear@0.0.1~start: Args: [ '-c', 'node netgear.js' ]
11 silly lifecycle netgear@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle netgear@0.0.1~start: Failed to exec start script
13 verbose stack Error: netgear@0.0.1 start: `node netgear.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid netgear@0.0.1
15 verbose cwd /mnt/c/Users/Flavien CADET/Documents/dev/netgearctl
16 verbose Linux 4.4.0-17763-Microsoft
17 verbose argv "/usr/bin/node" "/usr/sbin/npm" "start"
18 verbose node v11.9.0
19 verbose npm  v6.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error netgear@0.0.1 start: `node netgear.js`
22 error Exit status 1
23 error Failed at the netgear@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
[imeniyu@odinn netgearctl]$
```

Here my code :

``` node
'use strict';

const Netgear = require('netgear');

let netgear = new Netgear();

async function login() {
	try {
		console.log("Log in...")
		return netgear.login('MyPasswordWasHere');
	} catch (error) {
		console.log(error);
	}
}

login().then(result=>{
	console.log("Logged in :", result);
	if(!result)
		process.exit(1);

	netgear.reboot().then(result=>{
		console.log(result);
	})
	.catch(err=>{
		console.error(err);
		process.exit(1);
	});
})
.catch(err=>{
	console.error(err);
	process.exit(1);
});
```

I search in the source code, and I found the configurationStarted method didn't work with my router.

I hope you can help me.
Thank you very much.

**Comment by gruijter** [comment]
Does a reboot from the Netgear Genie app work?

And could you post the result of doing (from cli): > npm test yourPassword

**Comment by shiipou** [comment]
> 
> 
> Does a reboot from the Netgear Genie app work?
> 
> And could you post the result of doing (from cli): > npm test yourPassword

Hi @gruijter,

It connect with the Genie App, but the reboot action doesn't seems to reboot the router.
The app to control the M1100 was not Genie App but NETGEAR Mobile.

Here the tests : 

```console
Testing now. Hang on.....
========== STARTING TEST ==========
Node version: v11.9.0
Netgear package version: 3.3.4
OS: linux 4.4.0-17763-Microsoft
trying to auto discover the router...
{ host: '192.168.1.254', port: 80 }
trying to login...
login method: 1
trying to getInfo...
no response code from router
{ lastResponse:
   `<?xml version='1.0' encoding='UTF-8' ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance" xmlns:xsd="http://www.w3.org/1999/XMLSchema"> <SOAP-ENV:Body> <SOAP-ENV:Fault> <faultcode xsi:type="xsd:string">SOAP-ENV:Client</faultcode> <faultstring xsi:type="xsd:string">501:Unsupported action</faultstring> </SOAP-ENV:Fault> </SOAP-ENV:Body> </SOAP-ENV:Envelope> ` }
{ SerialNumber: '************' }
trying to get supportFeatures...
no response code from router
{ lastResponse:
   `<?xml version='1.0' encoding='UTF-8' ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance" xmlns:xsd="http://www.w3.org/1999/XMLSchema"> <SOAP-ENV:Body> <SOAP-ENV:Fault> <faultcode xsi:type="xsd:string">SOAP-ENV:Client</faultcode> <faultstring xsi:type="xsd:string">501:Unsupported action</faultstring> </SOAP-ENV:Fault> </SOAP-ENV:Body> </SOAP-ENV:Envelope> ` }
{}
trying to get Parental Control Status...
Config started error: Error: HTTP request Failed. Status Code: 401
{ lastResponse: 401 }
Parental Control Enabled: [object Object]
trying to get Qos Status...
Config started error: Error: HTTP request Failed. Status Code: 401
{ lastResponse: 401 }
Qos Enabled: [object Object]
trying to get Qos Bandwidth options...
no response code from router
{ lastResponse:
   `<?xml version='1.0' encoding='UTF-8' ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance" xmlns:xsd="http://www.w3.org/1999/XMLSchema"> <SOAP-ENV:Body> <SOAP-ENV:Fault> <faultcode xsi:type="xsd:string">SOAP-ENV:Client</faultcode> <faultstring xsi:type="xsd:string">501:Unsupported namespace</faultstring> </SOAP-ENV:Fault> </SOAP-ENV:Body> </SOAP-ENV:Envelope> ` }
{}
trying to get Device Access Control Status...
HTTP request Failed. Status Code: 401
{ lastResponse: 401 }
Block Device Enabled: [object Object]
trying to get attachedDevices...
Number of attached devices: 8, method: 1
First attached device: {"IP":"192.168.1.253","Name":"","MAC":"70:BB:E9:E4:86:1B","ConnectionType":"wireless","Linkspeed":100,"SignalStrength":100,"AllowOrBlock":"Allow"}
trying to get Guest Wifi Status...
2.4G-1 Guest wifi is not available
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
trying to get the Traffic Meter Enabled Status...
Unauthorized. Incorrect username/password?
{ lastResponse:
   '<?xml version="1.0" encoding="UTF-8" ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <SOAP-ENV:Body> <ResponseCode>401</ResponseCode> </SOAP-ENV:Body> </SOAP-ENV:Envelope>' }
Traffic Meter Enabled: [object Object]
trying to get the Traffic Meter Options...
Not logged in
{ lastResponse:
   '<?xml version="1.0" encoding="UTF-8" ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <SOAP-ENV:Body> <ResponseCode>401</ResponseCode> </SOAP-ENV:Body> </SOAP-ENV:Envelope>' }
{}
trying to get trafficMeter...
Not logged in
{ lastResponse:
   '<?xml version="1.0" encoding="UTF-8" ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <SOAP-ENV:Body> <ResponseCode>401</ResponseCode> </SOAP-ENV:Body> </SOAP-ENV:Envelope>' }
{}
trying to check newFirmware...
Not logged in
{ lastResponse:
   '<?xml version="1.0" encoding="UTF-8" ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <SOAP-ENV:Body> <ResponseCode>401</ResponseCode> </SOAP-ENV:Body> </SOAP-ENV:Envelope>' }
{}
trying to logout...
Not logged in
{ lastResponse:
   '<?xml version="1.0" encoding="UTF-8" ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <SOAP-ENV:Body> <ResponseCode>401</ResponseCode> </SOAP-ENV:Body> </SOAP-ENV:Envelope>' }
NetgearRouter {
  host: '192.168.1.254',
  port: 80,
  username: 'admin',
  password: '*******',
  timeout: 20000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: undefined,
  loggedIn: false,
  configStarted: false,
  soapVersion: 2,
  loginMethod: 1,
  getAttachedDevicesMethod: 1,
  guestWifiMethod: { set24_1: undefined, get50_1: 1, set50_1: undefined },
  lastResponse:
   '<?xml version="1.0" encoding="UTF-8" ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <SOAP-ENV:Body> <ResponseCode>401</ResponseCode> </SOAP-ENV:Body> </SOAP-ENV:Envelope>' }
test finished with 11 errors
```

Thank you again.

**Comment by gruijter** [comment]
Looks like your router is not compatible with the soap interface that the genie app is using. Is the discovered ip address and soap port correct? (192.168.1.254:80).

If not, set ip and port manually. > npm test password admin ip soapport

**Comment by gruijter** [comment]
Oh, and you must run it from within the lan part of the router, not from outside! I Saw your post on pynetgear. Does pynetgear work? If it does then you should at least get some resuls from netgear.js as well.

**Comment by shiipou** [comment]
Yes, it correct, I think the soap interface has différent methods than the soap interface of the genie app.

I can get the connected devices info and router info, but not all the informations.

Did you know what is the URI to get the WSDL of the router ?

Thank you again.

**Comment by gruijter** [comment]
I dont. Netgear doesnt comply to the common soap standards, and they do not provide any documentation. Maybe you can find info in the firmware file. See https://github.com/MatMaul/pynetgear/issues/20

**Comment by gruijter** [comment]
Still weird that you do get router info from pynetgear, and not from netgear.js. My netgear.js implementation uses the exact same soap commands. Maybe you should give the router a hard reset before starting the test. And update netgear.js to 3.3.5 while you are at it :)

**Comment by shiipou** [comment]
Hi, I solved my problem with a little hacky script I've just make : 

```javascript
/**
 * Base Vars
 */
const PASSWORD = "MyVerySecuredPassword";

/**
 * Connexion Vars
 */
const SCHEMA = "http";
const HOST = 'm.home';
const ROUTER_URI = SCHEMA + '://' + HOST;

/**
 * API Vars
 */
const API_URI = ROUTER_URI + '/api';
const MODEL_URI = API_URI + '/model.json';
const INTERNALAPI = '?internalapi=1'
const CONFIG_URI = ROUTER_URI + '/Forms/config';

/* Get the Request Object to call Router */
const r = require('request');

let token = null; // Token to connect to router
let user_role = null;

let jar = r.jar(); //Cookie jar

r({
    method: 'GET',
    url: MODEL_URI + INTERNALAPI,
    jar: jar
}, (err, resp, body) => {
    if (err) throw new Error(err);

    let json = JSON.parse(body);
    token = json.session.secToken;
    user_role = json.session.userRole;
    console.log('4G status:', json.wwan.connection);
    if (json.wwan.connection != 'Connected') {
        if (user_role == 'Guest') {
            r.post({
                url: CONFIG_URI,
                jar: jar,
                form: {
                    "token": token,
                    "session.password": PASSWORD
                }
            }, function (err, resp, body) {
                if (err) throw new Error(err);

                r({
                    method: 'GET',
                    url: MODEL_URI + INTERNALAPI,
                    jar: jar
                }, (err, resp, body) => {
                    if (err) throw new Error(err);

                    let json = JSON.parse(body);
                    token = json.session.secToken;
                    user_role = json.session.userRole;

                    console.log('Connected as', user_role);
                    if (user_role == 'Admin') {
                        r.post({
                            url: CONFIG_URI,
                            jar: jar,
                            form: {
                                "token": token,
                                "general.shutdown": "restart"
                            }
                        }, function (err, resp, body) {
                            if (err) throw new Error(err);
                            console.log("Restarting...");
                        });
                    }
                });
            });
        }
    }
});
```

The Netgear Nighthawk is not totally the same implementation of the soap API, so I use the web interface  to find the REST route I can use, My script is just a simulator of a web navigation and it just send the request like the navigator.

Thank you Gruijter.

**Comment by SamsGuamejy** [comment]
> Hi, I solved my problem with a little hacky script I've just make :
> 
> ```js
> /**
>  * Base Vars
>  */
> const PASSWORD = "MyVerySecuredPassword";
> 
> /**
>  * Connexion Vars
>  */
> const SCHEMA = "http";
> const HOST = 'm.home';
> const ROUTER_URI = SCHEMA + '://' + HOST;
> 
> /**
>  * API Vars
>  */
> const API_URI = ROUTER_URI + '/api';
> const MODEL_URI = API_URI + '/model.json';
> const INTERNALAPI = '?internalapi=1'
> const CONFIG_URI = ROUTER_URI + '/Forms/config';
> 
> /* Get the Request Object to call Router */
> const r = require('request');
> 
> let token = null; // Token to connect to router
> let user_role = null;
> 
> let jar = r.jar(); //Cookie jar
> 
> r({
>     method: 'GET',
>     url: MODEL_URI + INTERNALAPI,
>     jar: jar
> }, (err, resp, body) => {
>     if (err) throw new Error(err);
> 
>     let json = JSON.parse(body);
>     token = json.session.secToken;
>     user_role = json.session.userRole;
>     console.log('4G status:', json.wwan.connection);
>     if (json.wwan.connection != 'Connected') {
>         if (user_role == 'Guest') {
>             r.post({
>                 url: CONFIG_URI,
>                 jar: jar,
>                 form: {
>                     "token": token,
>                     "session.password": PASSWORD
>                 }
>             }, function (err, resp, body) {
>                 if (err) throw new Error(err);
> 
>                 r({
>                     method: 'GET',
>                     url: MODEL_URI + INTERNALAPI,
>                     jar: jar
>                 }, (err, resp, body) => {
>                     if (err) throw new Error(err);
> 
>                     let json = JSON.parse(body);
>                     token = json.session.secToken;
>                     user_role = json.session.userRole;
> 
>                     console.log('Connected as', user_role);
>                     if (user_role == 'Admin') {
>                         r.post({
>                             url: CONFIG_URI,
>                             jar: jar,
>                             form: {
>                                 "token": token,
>                                 "general.shutdown": "restart"
>                             }
>                         }, function (err, resp, body) {
>                             if (err) throw new Error(err);
>                             console.log("Restarting...");
>                         });
>                     }
>                 });
>             });
>         }
>     }
> });
> ```
> 
> The Netgear Nighthawk is not totally the same implementation of the soap API, so I use the web interface to find the REST route I can use, My script is just a simulator of a web navigation and it just send the request like the navigator.
> 
> Thank you Gruijter.

Tanks for your code!
I transform this for send SMS with my M2100 router ;-)
